@url = http://localhost:1337
### Variables
# @token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzYyNzcyMTExLCJleHAiOjE3NjUzNjQxMTF9._Lvx3BYAP7Da3FIxH8ih1QWCQOSEQMPK3vMjeMOrWoU

### Hardcoded
@token = e40114d4eb43c2d36fa3828789e23a4bbd4979550c0c9a233c8deb97eca9fab8e88c36d8f2f75344ebbd867aa21f3de8e0d37a207c168138792dc8124d779d8326c20a68b9c811852947330b907100ec3910234febec15f6e887b7dd1b358d9a82cb3584b2139ce07da92232740993f270bb4b382fd7b5769677a423894d6460

### Auth
POST {{url}}/api/auth/local/register
Content-Type: application/json

{
  "username": "thomas",
  "email": "thomas.lafarce@gmail.com",
  "password": "8hfds/f!ndfs"
}

### Auth
POST {{url}}/api/auth/local/register
Content-Type: application/json

{
  "username": "foobar",
  "email": "foo.bar@strapi.io",
  "password": "Test1234"
}

### Login
POST {{url}}/api/auth/local
Content-Type: application/json

{
  "identifier": "thomas",
  "password": "8hfds/f!ndfs"
}

### Get Me
GET {{url}}/api/users/me
Authorization: Bearer {{token}}

### Get recipes
GET {{url}}/api/recipes
Authorization: Bearer {{token}}

### Create recipe
POST {{url}}/api/recipes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "data": {
    "title": "Pancakes au sirop d'érable",
    "price": 1,
    "time": 2,
    "difficulty": 1
  }
}

### Create recipe
POST {{url}}/api/recipes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "data": {
    "title": "Salade de fruits",
    "price": 1,
    "time": 2,
    "difficulty": 1
  }
}

### Create recipe
POST {{url}}/api/recipes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "data": {
    "title": "Bouillabaisse",
    "price": 3,
    "time": 3,
    "difficulty": 2
  }
}

### Create recipe
POST {{url}}/api/recipes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "data": {
    "title": "Lapin au civet",
    "price": 2,
    "time": 3,
    "difficulty": 1
  }
}

### Update recipe
PUT {{url}}/api/recipes/bnn6eircdd3tpqsnmt657ylm
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "data": {
    "difficulty": 2
  }
}

### Delete recipe
DELETE {{url}}/api/recipes/bnn6eircdd3tpqsnmt657ylm
Authorization: Bearer {{token}}

### Get recipes where price is 1
GET {{url}}/api/recipes?filters[price][$eq]=1
Authorization: Bearer {{token}}